name: Style and package checks

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  FORCE_COLOR: "3"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  check:
    name: ${{ matrix.session == 'lint' && 'Style check' || 'Package check' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session:
        - lint
        - validate-package
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      with:
        persist-credentials: false
    - name: Install uv and dependencies
      uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
      with:
        enable-cache: true
        python-version: 3.11

    - name: Run ${{ matrix.session }}
      env:
        MATRIX_SESSION: ${{ matrix.session }}
      run: |
        uv sync --all-extras --dev
        uvx nox -s ${MATRIX_SESSION}
