name: Style and package checks

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
  workflow_dispatch:

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  FORCE_COLOR: "3"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  check:
    name: ${{ matrix.session == 'lint' && 'Style check' || 'Package check' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        session:
        - lint
        - validate-package
    steps:
    - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    - name: Install uv and dependencies
      uses: astral-sh/setup-uv@v6
      with:
        enable-cache: true
        python-version: 3.11

    - name: Run ${{ matrix.session }}
      run: |
        uv sync --locked --all-extras --dev
        uvx nox -s ${{ matrix.session }}
