name: Checks

on:
  pull_request:
    branches:
    - master
  push:
    branches:
    - master

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  PY_COLORS: '1'

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        env:
        #- ruff
        - package
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5.1.1
      with:
        python-version: '3.10'
    - name: Install build tools
      run: |
        python -m pip install tox wheel
    - name: Run ${{ matrix.env }}
      run: python -m tox -e ${{ matrix.env }}
