name: Publish

on:
  workflow_dispatch:
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: false

permissions: {}

env:
  PIP_DISABLE_PIP_VERSION_CHECK: '1'
  FORCE_COLOR: '3'

jobs:
  build:
    name: Build sdist and wheel
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
      name: Checkout repository
      with:
        persist-credentials: false

    - uses: actions/setup-python@ece7cb06caefa5fff74198d8649806c4678c61a1 # v6.3.0
      with:
        python-version: "3.12"

    - name: Install build tools
      run: |
        pipx run build --outdir dist

    - name: Upload wheel and sdist artifacts
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7.0.1
      with:
        name: artifacts
        path: ./dist/*
        if-no-files-found: error

  publish:
    needs: [build]
    name: Upload to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
      url: https://pypi.org/p/autograd
    permissions:
      id-token: write # mandatory for trusted publishing

    steps:
      - name: Download artifacts
        uses: actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c # v8.0.1
        with:
          path: dist
          merge-multiple: true

      - name: Sanity check artifacts
        run: ls -la dist/

      - name: Publish sdist and wheel to PyPI
        uses: pypa/gh-action-pypi-publish@cef221092ed1bacb1cc03d23a2d87d1d172e277b # v1.14.0
        with:
          packages-dir: dist/
