name: CI

on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
  workflow_dispatch:
  schedule:
    - cron: "0 4 * * *"

env:
  PIP_DISABLE_PIP_VERSION_CHECK: "1"
  FORCE_COLOR: "3"

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}

jobs:
  test:
    name: Regular tests / ${{ matrix.platform }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04-arm, macos-15-intel, macos-latest, windows-latest]
        python-version:
          ["3.10", "3.11", "3.12", "3.13", "3.14", "pypy-3.10"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}

      # On PyPy, we skip SciPy because we don't have wheels
      # available, see noxfile.py for more details.
      - name: Run tests
        run: uvx nox -s tests

  # In this job, we test against the NumPy nightly wheels hosted on
  # https://anaconda.org/scientific-python-nightly-wheels/numpy
  # on the latest Python version available across platforms, instead of
  # testing all Python versions and implementations on all platforms.
  # We do not test on PyPy.
  #
  # However, "nox -s nightly-tests" can be used locally anywhere, on
  # any Python version and implementation on any platform and we leave
  # it to the user to decide what Python version to test against, which
  # might or might not have a corresponding NumPy nightly wheel present.
  nightlies:
    name: Nightly tests / ${{ matrix.platform }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.platform }}
    strategy:
      fail-fast: false
      matrix:
        platform: [ubuntu-latest, ubuntu-22.04-arm, macos-15-intel, macos-latest, windows-latest]
        python-version: ["3.x"]

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run tests against nightly wheels for NumPy and SciPy
        run: uvx nox -s nightly-tests

  free-threaded-testing:
    name: "Free-threading tests / ${{ matrix.platform }} / Python ${{ matrix.python-version }} / Plugin ${{ matrix.pytest-plugin }}"
    runs-on: ${{ matrix.platform }}
    timeout-minutes: 30
    env:
      PYTHON_GIL: "0"
    strategy:
      fail-fast: false
      matrix:
        platform:
          [
            ubuntu-latest,
            ubuntu-22.04-arm,
            macos-15-intel,
            macos-latest,
            windows-latest,
          ]
        python-version: ["3.14t"]
        pytest-plugin: ["none", "pytest-run-parallel"]
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@fac544c07dec837d0ccb6301d7b5580bf5edae39 # v8.2.0
        with:
          python-version: ${{ matrix.python-version }}

      # 1) Test suite with free-threading enabled, but no free-threading-specific plugins
      - name: Run free-threaded tests on ${{ matrix.platform}}
        if: ${{ matrix.pytest-plugin == 'none' }}
        run: uvx nox -s free-threading

      # 2) Test suite with free-threading enabled, plus pytest-run-parallel plugin
      - name: Run free-threaded tests with ${{ matrix.pytest-plugin }} on ${{ matrix.platform}}
        if: ${{ matrix.pytest-plugin == 'pytest-run-parallel' }}
        run: uvx nox -s free-threading-pytest-run-parallel -- -sra --parallel-threads 4
